title: Your awesome page title
description: a short description for your self. cool.
email: your-email@example.com
github_username:  jekyll
linkedin_username: jekyll
blog: https://en.wikipedia.org/wiki/Blog
resume: assets/resume.pdf

name: James Clerk Maxwell
profile-photo: assets/img/head.png
background-img: img/bg.jpg

# Build settings
theme: minima
plugins:
  - jekyll-feed
